# Vector Database from scratch
A vector database is a collection of data stored as mathematical representations. Vector databases make it easier for machine learning models to remember previous inputs, allowing machine learning to be used to power search, recommendations, and text generation use-cases. Data can be identified based on similarity metrics instead of exact matches, making it possible for a computer model to understand data contextually.

In [22]:
import torch

In [23]:
from collections import defaultdict
import hashlib as cryptolib
import numpy as np
from typing import Dict, Set, List, Tuple, Union
import torch
from torch import Tensor

class VectorDB:
    def __init__(self) -> None:
        self.vector_documents: Dict[str, Tensor] = {}
        self.document_ids: Set[str] = set()

    def add_document(self, document: Dict[str, Union[str, Tensor]]) -> None:
        doc_id: str = document['id']
        doc_embedding: Tensor = document['text_embedding']

        if doc_id not in self.document_ids:
            self.document_ids.add(doc_id)
            self.vector_documents[doc_id] = doc_embedding
        else:
            print(f"Document with {doc_id} already exists in Database, Skipping")

    def create_document(self, text: str, embedding: Tensor) -> None:
        document_hash: str = cryptolib.md5(text.encode('utf-8')).hexdigest()
        new_document: Dict[str, Union[str, Tensor]] = {
            'id': document_hash,
            'text_embedding': embedding
        }
        self.add_document(new_document)

    def find_similarity(self, embedding1: Tensor, embedding2: Tensor) -> float:
        cos_similarity_score: float = torch.dot(embedding1.flatten(), embedding2.flatten()) / (
            torch.norm(embedding1) * torch.norm(embedding2)
        )
        return float(cos_similarity_score)

    def find_similar_documents(
        self,
        query_document: Dict[str, Union[str, Tensor]],
        similarity_threshold: float = 0.5
    ) -> List[Tuple[str, float]]:
        similar_docs: List[Tuple[str, float]] = []

        for id, text_embedding in self.vector_documents.items():
            similarity = self.find_similarity(
                query_document['text_embedding'],
                text_embedding.flatten()
            )
            if similarity > similarity_threshold:
                similar_docs.append((id, similarity))

        similar_docs.sort(key=lambda x: x[1], reverse=True)
        return similar_docs

    def __len__(self) -> int:
        return len(self.vector_documents)

In [24]:
myDB = VectorDB()


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer as tfidfV


In [26]:
docs = ["hello world!","ello Sam!","Sam is part of world!","ello Sameer!","hellow Sam!"]
docs2 = ["ello world!"]
my_vec = tfidfV()
my_vec.fit(docs)
embedding = my_vec.transform(docs2)
embedding.data

array([0.70710678, 0.70710678])

In [27]:
docs2[0]

'ello world!'

In [28]:
myDB.create_document(docs2[0],torch.tensor(embedding.toarray()))

In [29]:
torch.tensor(embedding.toarray()).flatten().dim()

1

In [30]:
print(myDB.vector_documents)

{'6e9bc20c0d778a0740d3e0396689909b': tensor([[0.7071, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7071]],
       dtype=torch.float64)}


In [31]:
print(myDB.find_similarity(torch.tensor(embedding.toarray()).flatten(),torch.tensor(embedding.toarray()).flatten()))

1.0000000000000002


In [32]:
for doc,embed in zip(docs,my_vec.transform(docs).toarray()):
  # print(tor.tensor(embed))
  myDB.create_document(doc,torch.tensor(embed))



In [33]:
myDB.vector_documents

{'6e9bc20c0d778a0740d3e0396689909b': tensor([[0.7071, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7071]],
        dtype=torch.float64),
 'fc3ff98e8c6a0d3087d515c0473f8677': tensor([0.0000, 0.7783, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6279],
        dtype=torch.float64),
 'ad47f4f07b6631c98d9fd9af32dc4257': tensor([0.7694, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6387, 0.0000, 0.0000],
        dtype=torch.float64),
 '12858b34d0a1ae7f62cab1726b8304c6': tensor([0.0000, 0.0000, 0.0000, 0.4939, 0.4939, 0.4939, 0.3308, 0.0000, 0.3985],
        dtype=torch.float64),
 'ed42f068740c5dc1b4071dd04c657444': tensor([0.6279, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7783, 0.0000],
        dtype=torch.float64),
 '40b72a3c4586ce1b6d5cc704161d2422': tensor([0.0000, 0.0000, 0.8309, 0.0000, 0.0000, 0.0000, 0.5565, 0.0000, 0.0000],
        dtype=torch.float64)}

In [34]:
input_list = ["ello Sam!"]

In [35]:
query = {'id':1,'text_embedding':torch.tensor(my_vec.transform(input_list).toarray()).flatten()}

In [36]:
query['text_embedding'].dim()

1

In [37]:
print(myDB.find_similar_documents(query))

[('ad47f4f07b6631c98d9fd9af32dc4257', 1.0), ('6e9bc20c0d778a0740d3e0396689909b', 0.5440812430630018)]


In [38]:
for id,embedding in myDB.vector_documents.items():
  print(my_vec.inverse_transform(embedding.reshape(-1,1)))

[array(['ello'], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array(['ello'], dtype='<U6')]
[array([], dtype='<U6'), array(['ello'], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array(['ello'], dtype='<U6')]
[array(['ello'], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array(['ello'], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6')]
[array([], dtype='<U6'), array([], dtype='<U6'), array([], dtype='<U6'), array(['ello'], dtype='<U6'), array(['ello'], dtype='<U6'), array(['ello'], dtype='<U6'), array(['ello'], dtype='<U6'), array([], dtype='<U6'), array(['ello'], dtype='<U6')]
[array(['ello'], dtype='<U6'), array([], dtype='<U6'), array([], d

In [39]:
myDB.vector_documents.get('ad47f4f07b6631c98d9fd9af32dc4257')

tensor([0.7694, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6387, 0.0000, 0.0000],
       dtype=torch.float64)

In [40]:
my_vec.decode(myDB.vector_documents.get('ad47f4f07b6631c98d9fd9af32dc4257').reshape(-1,1))

tensor([[0.7694],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.6387],
        [0.0000],
        [0.0000]], dtype=torch.float64)